@Library('jenkins-shared-library') _ 

pipeline {
    agent any 

    stages {
        stage('CI/CD') {
            steps {
                script {
                    runServicePipeline()
                }
            }
        }
    }
}